# This file lists the dependencies needed to build and test all of libeantic.
# Create a Conda environment with these dependencies preinstalled with:
# conda env create -f environment-flint2.yml
name: e-antic-build
channels:
  - conda-forge
dependencies:
  - arb
  - antic
  - automake
  - benchmark
  - byexample>=10.4
  - boost-cpp
  # Our byexample setup uses cppyy to run C++ code samples.
  - cppyy>=3,<4
  - coreutils
  - c-compiler
  - cxx-compiler
  - libflint=2
  - gmp
  - libtool
  - make
  - py
  # valgrind is only needed for make check-valgrind
  # - valgrind
