# This file lists the dependencies needed to build the documentation of
# e-antic.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -f libeantic/environment.yml
# conda env update -n doc-eantic-build -f pyeantic/environment.yml
# conda env update -n doc-eantic-build -f doc/environment.yml
name: doc-eantic-build
channels:
  - conda-forge
  - defaults
dependencies:
  - standardese
  - sphinx
  - mkdocs
  - pip
  - pip:
    - sphinx_rtd_theme
