# This file lists the dependencies needed to build the documentation of
# e-antic.
# Create a conda environment with these dependencies preinstalled with:
# conda env create -n doc-eantic-build -f libeantic/environment.yml
# conda env update -n doc-eantic-build -f pyeantic/environment.yml
# conda env update -n doc-eantic-build -f doc/environment.yml
name: doc-eantic-build
channels:
  - saraedum
  - conda-forge
dependencies:
  - standardese>=0.6.0
  - sphinx
  - mkdocs>=1.1.0
  - linkchecker
  - sphinx_rtd_theme
  # Some sphinx contrib packages are using
  # pkg_resources.declare_namespace which is obsolete. This leads to
  # warnings that make the doctests fail. We install a version of
  # setuptools that does not show these warnings to work around the
  # problem.
  - setuptools=67.1.0
