{% set version = '1.0.3' %}
{% set build_number = '1' %}

package:
  name: libeantic
  version: {{ version | replace("-", "") | replace("rc.", "rc") | replace("beta.", "beta") }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # dependency antic is not available for Windows on conda-forge
  skip: True  # [win]
  run_exports:
    - {{ pin_subpackage("libeantic") }}

requirements:
  build:
    - libtool
    - automake
    - {{ compiler('cxx') }}
  host:
    - antic
    - boost-cpp {{ boost_cpp }}
    - gmp {{ gmp }}
    - arb {{ arb }}
    - libflint {{ libflint }}

test:
  commands:
    - test -f $PREFIX/include/e-antic/e-antic.h  # [linux or osx]
    - test -f $PREFIX/lib/libeantic.so           # [linux]
    - test -f $PREFIX/lib/libeanticxx.so         # [linux]
    - test -f $PREFIX/lib/libeantic.dylib        # [osx]
    - test -f $PREFIX/lib/libeanticxx.dylib      # [osx]

about:
  home: https://github.com/flatsurf/e-antic
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: embedded algebraic number fields
  description: |
    e-antic is a C/C++ library to deal with real embedded number fields built
    on top of ANTIC. Its aim is to have as fast as possible exact arithmetic
    operations and comparisons.
  dev_url: https://github.com/flatsurf/e-antic
