{% set version = '1.0.3' %}
{% set build_number = '1' %}

package:
  name: pyeantic
  version: {{ version | replace("-", "") | replace("rc.", "rc") | replace("beta.", "beta") }}

source:
  path: ../../

build:
  number: {{ build_number }}
  # dependency antic is not available for Windows on conda-forge
  skip: True  # [win]

requirements:
  build:
    - libtool
    - automake
    - coreutils
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - cppyythonizations
    - libeantic
  run:
    - python
    - cppyy >=2.1.0,<3
    - cppyythonizations
    - boost-cpp
    # See https://github.com/flatsurf/e-antic/issues/223
    - cysignals <1.11.0  # [osx]

test:
  imports:
    - pyeantic

about:
  home: https://github.com/flatsurf/e-eantic
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: embedded algebraic number fields
