# This environment.yml can be used to create a conda environment with
# e-antic and all its dependencies installed. It is used for our demo
# binders.
name: binder
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets
  - notebook
  - libeantic
  - pyeantic
  - xeus-cling
