name: Benchmark
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  asv:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest" }
      - name: Install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libeantic/environment.yml
          conda list
      - name: Checkout historic performance data
        uses: actions/checkout@v2
        with:
          path: .asv/results
          ref: asv
      - name: Run benchmarks
        uses: flatsurf/actions/asv@main
      - name: Update historic performance data
        uses: EndBug/add-and-commit@v5
        with:
          author_name: asv bot
          author_email: bot@flatsurf.org
          message: 'record asv run'
          cwd: .asv/results
          branch: asv
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'push' }}
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .asv/html
          TARGET_FOLDER: asv
        if: ${{ github.event_name == 'push' }}

env:
  MAKEFLAGS: -j2
