name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.8.1
        with: { pixi-version: v0.30.0 }
      - run: |
          pixi run -e doc build-doc
          touch doc/manual/generated/html/.nojekyll
      - name: detect broken links
        run: pixi run -e doc test-doc-linkchecker
      - uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/manual/generated/html/e-antic
          TARGET_FOLDER: docs
        if: ${{ github.event_name == 'push' }}
