name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f doc/manual/environment.yml
          conda list
      - name: pyeantic inventory
        shell: bash -l {0}
        run: |
          cd doc/manual/sphinx
          make json
      - name: libeantic documentation
        shell: bash -l {0}
        run: |
          cd doc/manual/standardese
          make html
      - name: pyeantic documentation
        shell: bash -l {0}
        run: |
          cd doc/manual/sphinx
          make html
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/manual
          TARGET_FOLDER: manual
        if: ${{ github.event_name == 'push' }}
