name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { miniforge-variant: "Mambaforge", miniforge-version: "latest", python-version: "3.10" }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f doc/environment.yml
          mamba env update --quiet -n test -f libeantic/environment.yml
          mamba env update --quiet -n test -f pyeantic/environment.yml
          conda list
      - name: build e-antic
        shell: bash -l {0}
        run: |
          echo "::group::bootstrap"
          ./bootstrap

          echo "::group::configure"
          ./configure --prefix=${CONDA_PREFIX} --without-benchmark --without-byexample

          echo "::group::make"
          make
      - name: build documentation
        shell: bash -l {0}
        run: |
          make html
          touch doc/manual/generated/html/.nojekyll
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory doc/manual/generated/html &
          sleep 1

          # Strangely, the linkchecker modules are installed writable and linkchecker then refuses to load them.
          chmod -R a-w `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"` || true

          # Do not fail if there are 302 redirects.
          # Ignore broken links on gmplib.org, they seem to be rate limiting GitHub.
          linkchecker --check-extern http://localhost:8880/e-antic/libeantic --no-warnings --ignore gmplib.org
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/manual/generated/html/e-antic
          TARGET_FOLDER: docs
        if: ${{ github.event_name == 'push' }}
