name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

jobs:
  build-manual:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libeantic/environment.yml
          mamba env update --quiet -n test -f pyeantic/environment.yml
          mamba env update --quiet -n test -f doc/environment.yml
          conda list
      - name: fix permissions
        shell: bash -l {0}
        run: |
          # Strangely, the linkchecker modules are installed writeable and linkchecker then refuses to load them.
          chmod -R a-w `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
      - name: build e-antic
        shell: bash -l {0}
        run: |
          echo "::group::bootstrap"
          ./bootstrap

          echo "::group::configure"
          ./configure --prefix=${CONDA_PREFIX} --without-benchmark --without-byexample

          echo "::group::make"
          make
      - name: build documentation
        shell: bash -l {0}
        run: |
          make html
      - name: detect broken links
        shell: bash -l {0}
        run: |
          python -m http.server 8880 --directory doc/generated/e-antic/html &
          sleep 1
          linkchecker --check-extern http://localhost:8880/libeantic
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/manual/html
          TARGET_FOLDER: manual
        if: ${{ github.event_name == 'push' }}
