name: Documentation
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-manual:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: prefix-dev/setup-pixi@v0.8.8
        with: { pixi-version: v0.42.1 }
      - run: |
          pixi run -e dev build-doc
          touch doc/manual/generated/html/.nojekyll
      - name: detect broken links
        run: pixi run -e dev test-doc-linkchecker
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: doc/manual/generated/html
          target-folder: docs
        if: ${{ github.event_name == 'push' }}
