name: Install with pip
on:
  push: { branches: [ "master" ] }
  pull_request: { branches: [ "master" ] }
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

concurrency:
  group: pip-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sdist:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with: { submodules: recursive }
      - uses: conda-incubator/setup-miniconda@v2
        with: { mamba-version: "*", channels: "flatsurf,conda-forge", channel-priority: true }
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f libeantic/environment.yml
          mamba env update --quiet -n test -f pyeantic/environment.yml
          conda list
      - name: boostrap autotool setup
        shell: bash -l {0}
        run: |
          ./bootstrap
      - name: create libeantic sdist
        shell: bash -l {0}
        run: |
          cd libeantic
          python setup.py sdist
      - name: create pyantic sdist
        shell: bash -l {0}
        run: |
          cd pyeantic
          python setup.py sdist
      - name: upload libeantic sdist
        uses: actions/upload-artifact@v2
        with:
          name: libeantic-sdist
          path:
            libeantic/dist/**
      - name: upload libeantic sdist
        uses: actions/upload-artifact@v2
        with:
          name: pyeantic-sdist
          path:
            pyeantic/dist/**
